services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_DB_DRIVER: postgresql
      CB_DB_HOST: postgresql
      CB_DB_PORT: 5432
      CB_DB_DATABASE: db
      CB_DB_USERNAME: dbuser
      CB_DB_PASSWORD: dbpwd
    ports:
      - 8001:8978
    depends_on:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8002:80
    depends_on:
      - postgresql

volumes:
  postgresql_data:
