services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_pass
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redislabs/redismod
    container_name: redis_recepty
    ports:
      - "6379:6379"

  flask:
    build: .
    container_name: flask_recepty
    environment:
      - FLASK_ENV=development
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_pass
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    depends_on:
      - db
      - redis

